FROM python:3.10-slim

# 1. Archive Repository Settings (if legacy)


# 2. System Dependencies
# 2. System Dependencies

RUN apt-get update && apt-get install -y --force-yes --allow-unauthenticated \
    libgl1 \
    libglib2.0-0 \
    python3-matplotlib \
    build-essential \
    cmake \
    python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# 3. Pip Configuration

RUN mkdir -p /root/.pip && \
    printf "[global]\ntrusted-host = pypi.python.org pypi.org files.pythonhosted.org\n" > /root/.pip/pip.conf


# 4. Python Libraries

RUN pip install --no-cache-dir \
"pandas" \
    "numpy" \
    "scikit-image" \
    "opencv-python"
    






ENV PYTHONUNBUFFERED="1"



WORKDIR /app
ENTRYPOINT ["python"]