FROM python:3.6-slim-stretch@sha256:15c2b35ce4a026d8d52bd4b8ff13904030c2f4c2809b4368f180390b1a18c284
# 1. Archive Repository Settings (if legacy)


# 2. System Dependencies
# 2. System Dependencies

RUN apt-get update && apt-get install -y --force-yes --allow-unauthenticated \
    libgl1-mesa-glx \
    libglib2.0-0 \
    cmake \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# 3. Pip Configuration

RUN mkdir -p /root/.pip && \
    printf "[global]\ntrusted-host = pypi.python.org pypi.org files.pythonhosted.org\n" > /root/.pip/pip.conf


# 4. Python Libraries

RUN pip install --no-cache-dir \
    "matplotlib" \
    "scikit-image" \
    "opencv-python-headless"
    






ENV PYTHONUNBUFFERED="1"



WORKDIR /app
ENTRYPOINT ["python"]
