FROM python:3.6-slim-buster

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Install Data Science stack (Pandas, Scikit-learn) compatible with Py3.6
# Python 3.6 EOL: Dec 2021.
# Pandas 1.1.5 is likely the last for Py3.6
# Scikit-learn 0.24.2 is likely the last for Py3.6
RUN pip install "numpy<1.20" "pandas<1.2" "scikit-learn<0.25"

WORKDIR /app
