FROM python:3.6-slim-stretch@sha256:15c2b35ce4a026d8d52bd4b8ff13904030c2f4c2809b4368f180390b1a18c284

# 1. Archive Repository Settings (if legacy)

RUN echo "deb http://archive.debian.org/debian/ stretch main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security/ stretch/updates main" >> /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until


# 2. System Dependencies
# 2. System Dependencies

RUN apt-get update && apt-get install -y --force-yes --allow-unauthenticated \
    libgomp1 \
    libatlas-base-dev \
    liblapack-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# 3. Pip Configuration

RUN mkdir -p /root/.pip && \
    printf "[global]\ntrusted-host = pypi.python.org pypi.org files.pythonhosted.org\n" > /root/.pip/pip.conf


# 4. Python Libraries

RUN pip install --no-cache-dir \
    "numpy<1.16" \
    "pandas==0.23.4" \
    "scipy==1.1.0" \
    "scikit-learn==0.19.2" \
    "matplotlib==2.2.3"
    






WORKDIR /app
ENTRYPOINT ["python"]

