from typing import Any, Dict, List, Optional, Protocol

from lcr.core.container.types import AnalysisResult, ImageRule, RunConfig
from lcr.core.history.types import ExecutionHistory


class ContainerManagerPort(Protocol):
    def get_available_runtimes(self) -> List[ImageRule]: ...
    def resolve_runtime(self, search_terms: List[str], version_hint: str) -> ImageRule: ...
    def synthesize_definition_config(self, analysis: Dict, rec_id: str) -> Dict: ...
    def reload_definitions(self) -> None: ...
    def validate_environment(self) -> None: ...
    def _check_version_compat(self, code_ver: str, rule_ver: str) -> bool: ...
    def prepare_run_config(
        self,
        analysis_result: AnalysisResult,
        script_path: str,
        data_dir: Optional[str] = None,
        output_dir: Optional[str] = None,
        override_image_rule: Optional[ImageRule] = None,
    ) -> RunConfig: ...
    def get_docker_run_args(self, config: RunConfig) -> List[str]: ...
    def get_definition(self, env_id: str) -> Optional[Dict]: ...
    def get_build_command(self, dockerfile_path: str, tag: str) -> List[str]: ...
    def commit_definition(self, def_id: str) -> bool: ...
    def rollback_definition(self, def_id: str) -> None: ...
    def _apply_legacy_pins(self, pip_pkgs: List[str], version: str) -> List[str]: ...


class AnalyzerPort(Protocol):
    def summary(self, code_text: str) -> Dict[str, Any]: ...
    def analyze(self, code_text: Optional[str] = None) -> Any: ...


class AuditMetadataPort(Protocol):
    def collect(self, image_name: str, script_path: str, script_path_rel: str) -> Dict[str, str]: ...


class HistoryManagerPort(Protocol):
    def save_record(self, record: ExecutionHistory) -> None: ...
    def load_history(self) -> List[ExecutionHistory]: ...
    def get_absolute_path(self, relative_path: str) -> str: ...
    def to_relative_path(self, path_str: str) -> str: ...
